{% if cookiecutter.use_docker== 'y' %}
docker:
  docker_pull:
    - quay.io/biocontainers/fastqc:0.11.8--1
    - quay.io/biocontainers/trimmomatic:0.39--1
    - quay.io/biocontainers/bwa:0.7.17--h84994c4_5
    - quay.io/biocontainers/bedtools:2.28.0--hdf88d34_0
    - quay.io/biocontainers/phantompeakqualtools:1.2--1
    - quay.io/biocontainers/samtools:1.9--h91753b0_8
    - quay.io/biocontainers/rseqc:3.0.0--py_3
    - quay.io/biocontainers/sra-tools:2.10.0--pl526he1b5a44_0
    - quay.io/biocontainers/igvtools:2.5.3--0
    - quay.io/biocontainers/mace:1.2--py27h99da42f_1
    - ubuntu:18.04
  docker_build:
    r-3.5_ubuntu-18.04:
      tag: latest
      dockerfile: https://raw.githubusercontent.com/ncbi/cwl-ngs-workflows-cbb/master/tools/R/Dockerfile_R-3.6_ubuntu-18.04
{% else %}
tools:
  - SRA-Tools:
      command: fastq-dump
      version: '2.10.0'
      option: --version
      out: stdout
  - Fastqc:
      command: fastqc
      version: 'v0.11.8'
      option: --version
      out: stdout
  - Trimmomatic:
      command: trimmomatic
      version: '0.39'
      option: -version
      out: stdout
  - BWA:
      command: bwa
      version: '0.7.17'
      out: stderr
  - Samtools:
      command: samtools
      version: '1.9'
      option: --version
      out: stdout
  - BEDtools:
      command: bedtools
      version: '2.28.0'
      option: --version
      out: stdout
  - Phantompeakqualtools:
      command: run_spp.R
  - Homer:
      command: homer
  - MACE:
      command: mace.py
      version: 'Usage: mace.py'
      out: stdout
  - R:
      command: R
      version: '3.5.1'
      option: --version
      out: stdout
{% endif %}