{% if cookiecutter.use_docker== 'y' %}
docker:
  docker_pull:
    - quay.io/biocontainers/fastqc:0.11.8--1
    - quay.io/biocontainers/trimmomatic:0.39--1
    - quay.io/biocontainers/star:2.7.3a--0
    - quay.io/biocontainers/samtools:1.9--h91753b0_8
    - quay.io/biocontainers/rseqc:3.0.0--py_3
    - quay.io/biocontainers/tpmcalculator:0.0.3--hdbb99b9_0
    - quay.io/biocontainers/igvtools:2.5.3--0
    - quay.io/biocontainers/sra-tools:2.10.0--pl526he1b5a44_0
    - ubuntu:18.04
  docker_build:
    r-3.5_ubuntu-18.04:
      tag: latest
      dockerfile: https://raw.githubusercontent.com/ncbi/cwl-ngs-workflows-cbb/master/tools/R/Dockerfile_R-3.6_ubuntu-18.04
  {% else %}
tools:
  - SRA-Tools:
      command: fastq-dump
      version: '2.10.0'
      option: --version
      out: stdout
  - Fastqc:
      command: fastqc
      version: 'v0.11.8'
      option: --version
      out: stdout
  - Trimmomatic:
      command: trimmomatic
      version: '0.39'
      option: -version
      out: stdout
  - STAR:
      command: STAR
      version: '2.7.3a'
      option: --version
      out: stdout
  - Samtools:
      command: samtools
      version: '1.9'
      option: --version
      out: stdout
  - TPMCalculator:
      command: TPMCalculator
      version: '0.0.3'
      option: -version
      out: stdout
  - RSeQC:
      command: bam_stat.py
      version: '3.0.0'
      option: --version
      out: stdout
  - igvtools:
      command: igvtools
      version: '2.5.3'
      out: stdout
  - R:
      command: R
      version: '3.5.1'
      option: --version
      out: stdout
  - Deseq2:
      command: Rscript
      output: '[1] TRUE'
      option:
        - -e
        - "'DESeq2' %in% rownames(installed.packages())"
      out: stdout
  - EdgeR:
      command: Rscript
      output: '[1] TRUE'
      option:
        - -e
        - "'edgeR' %in% rownames(installed.packages())"
      out: stdout
  - ggplot2:
      command: Rscript
      output: '[1] TRUE'
      option:
        - -e
        - "'ggplot2' %in% rownames(installed.packages())"
      out: stdout
{% endif %}